<img src="images/usm.jpg" width="480" height="240" align="left"/>

# MAT281 - Laboratorio N°02

## Objetivos de la clase

* Reforzar los conceptos básicos de numpy.

## Contenidos

* [Problema 01](#p1)
* [Problema 02](#p2)
* [Problema 03](#p3)

In [2]:
import numpy as np
import time
import sys

<a id='p1'></a>

## Problema 01

Una **media móvil simple** (SMA) es el promedio de los últimos $k$ datos anteriores, es decir, sea $a_1$,$a_2$,...,$a_n$ un arreglo $n$-dimensional, entonces la SMA se define por:

$$sma(k) =\dfrac{1}{k}(a_{n}+a_{n-1}+...+a_{n-(k-1)}) = \dfrac{1}{k}\sum_{i=0}^{k-1}a_{n-i}  $$ 


Por otro lado podemos definir el SMA con una venta móvil de $n$ si el resultado nos retorna la el promedio ponderado avanzando de la siguiente forma:

* $a = [1,2,3,4,5]$, la SMA con una ventana de $n=2$ sería:


    * sma(2): [mean(1,2),mean(2,3),mean(3,4)] = [1.5, 2.5, 3.5, 4.5]
    * sma(3): [mean(1,2,3),mean(2,3,4),mean(3,4,5)] = [2.,3.,4.]


Implemente una función llamada `sma` cuyo input sea un arreglo unidimensional $a$ y un entero $n$, y cuyo ouput retorne el valor de la media móvil simple sobre el arreglo de la siguiente forma:

* **Ejemplo**: *sma([5,3,8,10,2,1,5,1,0,2], 2)* = $[4. , 5.5, 9. , 6. , 1.5, 3. , 3. , 0.5, 1. ]$

En este caso, se esta calculando el SMA para un arreglo con una ventana de $n=2$.

**Hint**: utilice la función `numpy.cumsum`

In [114]:
def sma(ndarray, n:int):
    
    """
    sma(ndarray,n)
    
    Aproximacion de Media Movil Simple (SMA) para un arreglo ndarray 
    unidimensional fijando una ventana n.
    
    Parameters
    ----------
    ndarray : np.array
        Arreglo unidimensional con elementos flotantes.
    n : int
        Orden de ventanas.
        
    Returns
    -------
    medida : np.array
        SMA de ndarray asociado a una ventana n.
        
    Examples
    --------
    >>> sma([1,2,3,4,5],2)
    [1.5, 2.5, 3.5, 4.5]
    
    >>> sma([1,2,3,4,5],3)
    [2.0, 3.0, 4.0]
    
    >>> sma([5,3,8,10,2,1,5,1,0,2],2)
    [4.0, 5.5, 9.0, 6.0, 1.5, 3.0, 3.0, 0.5, 1.0]   
    """
    ndarray=np.array(ndarray)
    if len(ndarray.shape)!=1:
        return "Error: el arreglo no es unidimensional"
    else:
        medida = np.array([]) # iniciamos un arreglo vacio para almacenar el calculo
        for elem in range(len(ndarray)):
            if len(ndarray)-elem<n: # si el largo del arreglo menos la posicion del elemento es menor que n entonces quiebra
                break
            array_aux = np.array([ndarray[elem+i] for i in range(n)]) # para cada elemento almacena una lista de n elementos hasta agotar stock
            medida = np.append(medida,np.mean(array_aux)) # a cada ventana de elementos se calcula la media ponderada y se añade al arreglo inicial

        return np.array(medida) 

In [7]:
# example 01
sma([1,2,3,4,5],2)

[1.5, 2.5, 3.5, 4.5]

In [8]:
# example 02
sma([1,2,3,4,5],3)

[2.0, 3.0, 4.0]

In [5]:
# example 03
sma([5,3,8,10,2,1,5,1,0,2], 2)

[4.0, 5.5, 9.0, 6.0, 1.5, 3.0, 3.0, 0.5, 1.0]

<a id='p2'></a>

## Problema 02

La función **strides($a,n,p$)**, corresponde a transformar un arreglo unidimensional $a$ en una matriz de $n$ columnas, en el cual las filas se van construyendo desfasando la posición del arreglo en $p$ pasos hacia adelante.

* Para el arreglo unidimensional $a$ = [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], la función strides($a,4,2$), corresponde a crear una matriz de $4$ columnas, cuyos desfaces hacia adelante se hacen de dos en dos. 

El resultado tendría que ser algo así:$$\begin{pmatrix}
 1& 2 &3 &4 \\ 
 3&  4&5&6 \\ 
 5& 6 &7 &8 \\ 
 7& 8 &9 &10 \\ 
\end{pmatrix}$$


Implemente una función llamada `strides(a,4,2)` cuyo input sea un arreglo unidimensional y retorne la matriz de $4$ columnas, cuyos desfaces hacia adelante se hacen de dos en dos. 

* **Ejemplo**: *strides($a$,4,2)* =$\begin{pmatrix}
 1& 2 &3 &4 \\ 
 3&  4&5&6 \\ 
 5& 6 &7 &8 \\ 
 7& 8 &9 &10 \\ 
\end{pmatrix}$


In [100]:
def strides(a:np.array, n:int, p:int)->np.array:
    
    """
    strides(a,n,p)
    
    Un arreglo unidimensional a se transforma en una matriz de n columnas cuyo 
    llenado de filas corresponde al desplazamiento de p pasos en el arreglo.
    
    Parameters
    ----------
    a : np.array
        Arreglo unidimensional con elementos flotantes.
    n : int
        Cantidad de columnas.
    p : int
        Pasos de desplazamiento en el arreglo a.
        
    Returns
    -------
    matrix : np.array
        Matriz de 4 columnas cuyas filas se llenan desplazando p veces los elementos de a.  

    Examples
    --------
    >>> strides([1, 2, 3, 4, 5, 6, 7, 8, 9, 10],4,2)
    array([[ 1.,  2.,  3.,  4.],
       [ 3.,  4.,  5.,  6.],
       [ 5.,  6.,  7.,  8.],
       [ 7.,  8.,  9., 10.]])
    """
    
    a = np.array(a)
    if len(a.shape)!=1: # si el arreglo a no es unidimensional entonces no se puede emplear la funcion
        return "Error: el arreglo no es unidimensional"
    
    else:
        matrix = np.zeros((int((len(a)-n+p)/p),n)) # creamos una matriz de ceros para luego reemplazar las filas
        for fila in range(int((len(a)-n+p)/p)+1):
            if fila>0: # si no estamos en la siguiente fila hacemos lo que sigue
                if len(a[fila*p:fila*p+n])>n: 
                    continue # si la fila supera el largo n entonces no hace nada (se salta a la siguiente fila)
                elif len(a[fila*p:fila*p+n])<n: 
                    break # si llegamos al final del arreglo y nos sobran menos de n terminos entonces la funcion se termina
                else: 
                    matrix[fila] = np.array(a[fila*p:fila*p+n]) # a cada fila distinta de la primera colocamos los terminos del arreglo segun el desplazamiento p, cada fila tiene un largo n
                    print("Fila "+str(fila+1)+": "+str(matrix[fila]))
            else:
                matrix[fila] = np.array(a[:n]) # la primera fila son los primeros n terminos del arreglo
                print("Fila "+str(fila+1)+": "+str(matrix[fila]))
                
        return matrix

In [101]:
# example 01
strides([1,2,3,4,5,6,7,8,9,10],4,2)

Fila 1: [1. 2. 3. 4.]
Fila 2: [3. 4. 5. 6.]
Fila 3: [5. 6. 7. 8.]
Fila 4: [ 7.  8.  9. 10.]


array([[ 1.,  2.,  3.,  4.],
       [ 3.,  4.,  5.,  6.],
       [ 5.,  6.,  7.,  8.],
       [ 7.,  8.,  9., 10.]])

<a id='p3'></a>

## Problema 03


Un **cuadrado mágico** es una matriz de tamaño $n \times n$ de números enteros positivos tal que 
la suma de los números por columnas, filas y diagonales principales sea la misma. Usualmente, los números empleados para rellenar las casillas son consecutivos, de 1 a $n^2$, siendo $n$ el número de columnas y filas del cuadrado mágico.

Si los números son consecutivos de 1 a $n^2$, la suma de los números por columnas, filas y diagonales principales 
es igual a : $$M_{n} = \dfrac{n(n^2+1)}{2}$$
Por ejemplo, 

* $A= \begin{pmatrix}
 4& 9 &2 \\ 
 3&  5&7 \\ 
 8& 1 &6 
\end{pmatrix}$,
es un cuadrado mágico.

* $B= \begin{pmatrix}
 4& 2 &9 \\ 
 3&  5&7 \\ 
 8& 1 &6 
\end{pmatrix}$, no es un cuadrado mágico.

Implemente una función llamada `es_cuadrado_magico` cuyo input sea una matriz cuadrada de tamaño $n$ con números consecutivos de $1$ a $n^2$ y cuyo ouput retorne *True* si es un cuadrado mágico o 'False', en caso contrario

* **Ejemplo**: *es_cuadrado_magico($A$)* = True, *es_cuadrado_magico($B$)* = False

**Hint**: Cree una función que valide que la mariz es cuadrada y  que sus números son consecutivos del 1 a $n^2$.

In [117]:
def es_cuadrado_magico(A:np.array)->bool:
    
    """
    es_cuadrado_magico(A)
    
    Una matriz A es un cuadrado magico cuando es una matriz cuadrada de orden n, 
    sus elementos son enteros positivos y la suma de sus diagonales principales, 
    filas y columnas es la misma. En general los terminos ordenados deben estar 
    distribuidos de forma natural de 1 a n**2.
    
    Parameters
    ----------
    A : np.array
        Matriz cuadrada con valores enteros positivos.
        
    Returns
    -------
    matrix : bool
        Valor de verdad que dice si A es un cuadrado magico o no.
        
    Examples
    --------
    >>> es_cuadrado_magico(np.array([[4,9,2],[3,5,7],[8,1,6]])
    True
    
    >>> es_cuadrado_magico(np.array([[4,2,9],[3,5,7],[8,1,6]]
    False
    """
    
    if len(A.shape)==2 and A.shape[0]==A.shape[1]: #verificamos si la matriz es cuadrada
        n = A.shape[0] # definimos n como el orden de la matriz
        Lista_Ordenada = np.sort(A, axis=None) # las entradas de la matriz A las ordenamos en un arreglo unidimensional
        aRange = np.arange(1,n**2+1,1,dtype=int) # creamos un arreglo unidimensional que va desde 1 hasta n**2
        comparacion = Lista_Ordenada==aRange # establecemos un booleano para la igualdad de los arreglos unidimensionales
        if n**2==(len(Lista_Ordenada)) and comparacion.any(): # Si el largo de la lista ordenada es n**2 y el booleano es verdadero entonces A puede ser cuadrado magico
            Suma_Magica = (n*(n**2+1))/2 # definimos la suma magica dada por la formula n*(n**2+1)/2
            contador_diagonal = 0 # contador de la suma diagonal principal inicializado
            for indice_diagonal in range(n):
                contador_diagonal+=A[indice_diagonal,indice_diagonal] # se suman los elementos de la diagonal principal
            if contador_diagonal!=Suma_Magica: # si la suma de la diagonal principal no es igual a la suma magica entonces A no es cuadrado magico
                print("La matriz "+str(A)+" no es un cuadrado magico")
                return False
            else: # realizamos las otras sumas
                contador_diagonal_sec = 0 # contador de la suma diagonal secundaria inicializado
                for indice_diagonal in range(n):
                    contador_diagonal_sec+=A[indice_diagonal,n-1-indice_diagonal] # se suman los elementos de la diagonal secundaria
                if contador_diagonal_sec!=Suma_Magica: # si la suma de la diagonal secundaria no es igual a la suma magica entonces A no es cuadrado magico
                    print("La matriz "+str(A)+" no es un cuadrado magico")
                    return False
                else: # realizamos las otras sumas
                    for fila in range(n):
                        contador_fila = 0 # contador de la suma de cada fila inicializado
                        for columna in range(n):
                            contador_fila+=A[fila,columna] # se suman los terminos de cada fila
                        if contador_fila!=Suma_Magica: # si la suma de cada fila no es la suma magica entonces la matriz A no es un cuadrado magico
                            print("La matriz "+str(A)+" no es un cuadrado magico")
                            return False
                        for columna in range(n):
                            contador_columna = 0 # contador de la suma de cada columna inicializado
                            for fila in range(n):
                                contador_columna+=A[fila,columna] # se suman los terminos de cada columna
                            if contador_columna!=Suma_Magica: # si la suma de cada columna no es la suma magica entonces la matriz A no es un cuadrado magico
                                print("La matriz "+str(A)+" no es un cuadrado magico")
                                return False
                        print("La matriz "+str(A)+" es un cuadrado magico") # si no retorno False anteriormente no tiene otra posibilidad mas que ser un cuadrado magico
                        return True
        else:
            print("La matriz "+str(A)+" no es un cuadrado magico")
            return False
    else: # si la matriz no es cuadrada no se puede usar el algoritmo
        print("Error: la matriz no es cuadrada")
        return False

In [118]:
# example 01
es_cuadrado_magico(np.array([[4,9,2],[3,5,7],[8,1,6]],dtype=int))

La matriz [[4 9 2]
 [3 5 7]
 [8 1 6]] es un cuadrado magico


True

In [119]:
# example 02
es_cuadrado_magico(np.array([[4,2,9],[3,5,7],[8,1,6]],dtype=int))

La matriz [[4 2 9]
 [3 5 7]
 [8 1 6]] no es un cuadrado magico


False